version: '3.8'

services:
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - 80:80
  backend:
    container_name: backend
    build: ./backend
    ports:
      - 8080:8080
